spring.application.name=subscription-auth-server
server.port=8081

# mysql
spring.datasource.url=jdbc:mysql://localhost:3306/subscription_auth?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=123qwe!@#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# data.sql 설정
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# redis 설정
spring.data.redis.host=redis-15617.crce284.ap-neast-2-1.ec2.cloud.redislabs.com
spring.data.redis.port=15617
spring.data.redis.username=default
spring.data.redis.password=hHsHnV1SMMiStCkDbkvhkgsCh3alQcfe
spring.data.redis.ssl.enabled=false

logging.level.org.springframework.security=DEBUG

# 환경변수
jwt.secret-key=hellomynameisnadankimthankyousirseeyoulater

#모니터링
management.endpoints.web.exposure.include=prometheus
