### 내 정보 탈퇴
DELETE http://localhost:8081/api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlVTRVIiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzczNzYxNzU3LCJleHAiOjE3NzM3NjM1NTd9.RNu0_s0UMPdJXRVulpZtOb2uqvVX3nwwGsQ2ePW-swA
